"""The Commands tab: every subcommand as a form, with Run and Stop.

The nine forms are generated by `cliform.build_command_form` from argparse itself,
so this module holds no knowledge of any individual flag -- it picks a command, hands
its argv to the runner, and reports what came back.

The one piece of real policy here is what happens when a command finishes: if it
wrote the graph the viewer currently has open, the panel offers to reload it and does
*not* do so on its own. Auto-reloading would fight you mid-inspection and would throw
away skeleton edits without asking. If it wrote a different graph, it offers to load
that instead -- the one-click loop that is the point of the whole panel.
"""

from __future__ import annotations

from pathlib import Path

from . import cliform
from .runner import Job

#: Inputs "Use loaded paths" must NOT fill in, per command.
#:
#: `pick-roots` reads the segmentation for one thing only -- anchoring the tree
#: numbering to the mask labelling -- and the roots it records are identical without
#: it, because they are recorded by world coordinate. Filling it in silently turns a
#: three-second command into a full decode plus a connected-component labelling, tens
#: of minutes at stride 1 on a whole heart. That is not a cost to hand someone for
#: pressing a button labelled "point this form at what the viewer has open".
SKIP_PREFILL = {"pick-roots": ("seg",)}


def build_commands_panel(app, runner, specs):
    """Return the Commands widget. ``specs`` is `describe_parser`'s output."""
    from qtpy.QtWidgets import (
        QComboBox,
        QFileDialog,
        QHBoxLayout,
        QLabel,
        QListWidget,
        QPushButton,
        QScrollArea,
        QStackedWidget,
        QVBoxLayout,
        QWidget,
    )

    box = QWidget()
    lay = QVBoxLayout(box)
    lay.setContentsMargins(8, 8, 8, 8)

    chooser = QComboBox()
    stack = QStackedWidget()
    forms: dict[str, QWidget] = {}
    last_dir = {}

    def browse(spec_name, field):
        role, filt = cliform.path_role(spec_name, field.dest)
        start = last_dir.get(role, str(getattr(app.args, "graph", "") or ""))
        if role == "dir":
            return QFileDialog.getExistingDirectory(box, f"Choose {field.label}", start)
        if role == "save_dir":
            return QFileDialog.getExistingDirectory(box, f"Choose {field.label}", start)
        if role == "save_file":
            chosen, _ = QFileDialog.getSaveFileName(
                box, f"Write {field.label} to", start, filt or "All files (*)")
        else:
            chosen, _ = QFileDialog.getOpenFileName(
                box, f"Choose {field.label}", start, filt or "All files (*)")
        if chosen:
            last_dir[role] = str(Path(chosen).parent)
        return chosen

    for spec in specs:
        # `on_changed` is attached after the Run button exists -- the handler needs it.
        form = cliform.build_command_form(
            spec,
            browse=lambda field, name=spec.name: browse(name, field),
        )
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setWidget(form)
        forms[spec.name] = form
        stack.addWidget(scroll)
        chooser.addItem(spec.name)

    chooser.currentIndexChanged.connect(stack.setCurrentIndex)
    lay.addWidget(chooser)
    lay.addWidget(stack, 1)

    problems = QLabel("")
    problems.setWordWrap(True)
    problems.setStyleSheet("color: #d08770;")
    lay.addWidget(problems)

    row = QHBoxLayout()
    run = QPushButton("Run")
    stop = QPushButton("Stop")
    prefill = QPushButton("Use loaded paths")
    prefill.setToolTip("Fill this form's graph, seg and edits fields from the dataset "
                       "currently open in the viewer.")
    for button in (run, stop, prefill):
        row.addWidget(button)
    row.addStretch(1)
    mode = QLabel("")
    mode.setStyleSheet("color: #808090;")
    row.addWidget(mode)
    lay.addLayout(row)

    queue = QListWidget()
    queue.setMaximumHeight(72)
    queue.setToolTip("Jobs waiting to run. One runs at a time - each writes files the "
                     "next one may read.")
    lay.addWidget(queue)

    # -- helpers ----------------------------------------------------------

    def current():
        return forms[chooser.currentText()]

    def _refresh_run() -> None:
        form = current()
        errors = form.errors()
        problems.setText("; ".join(errors))
        run.setEnabled(not errors and not runner.busy)
        argv = form.argv()
        where = "in this process" if _mode(argv) == "inproc" else "as a child process"
        mode.setText(f"runs {where}")

    def _mode(argv):
        from .runner import mode_for

        return mode_for(argv)

    def do_run() -> None:
        form = current()
        if form.errors():
            return
        argv = form.argv()
        values = form.values()
        outputs = tuple(
            str(values[dest]) for dest in ("out", "out_dir")
            if values.get(dest) and form.spec.field(dest) is not None
        )
        runner.submit(Job(argv=argv, label=argv[0], outputs=outputs))

    def do_prefill() -> None:
        """Point this form at what the viewer has open."""
        form = current()
        wanted = {}
        # `--graph` may now be several paths. Every command form but `pick-roots`
        # takes exactly one, so prefill the first and let the operator pick another:
        # silently handing a one-graph command the left tree when they were looking at
        # both would be worse than making them choose.
        from .main import graph_paths

        loaded = graph_paths(app.args.graph)
        first = loaded[0] if loaded else ""
        # `voxel_um` travels with the paths, and has to: a command run without it
        # works in the files' own micrometres while the viewer works in the corrected
        # ones, and the radii it writes would come back a few percent adrift from
        # everything measured beside them.
        for dest, value in (("graph", first), ("seg", app.args.seg),
                            ("edits", app.args.edits), ("reference", first),
                            ("voxel_um", getattr(app.args, "voxel_um", None))):
            if dest in SKIP_PREFILL.get(form.spec.name, ()):
                continue
            field = form.spec.field(dest)
            if value and field is not None:
                wanted[dest] = (list(loaded) if field.repeatable and field.positional
                                else str(value))
        form.set_values(wanted)

    def do_stop() -> None:
        runner.stop()

    run.clicked.connect(do_run)
    stop.clicked.connect(do_stop)
    prefill.clicked.connect(do_prefill)
    stop.setToolTip(
        "Clears the queue, and kills the job if it is a child process.\n"
        "A job running in this process has no cancellation point, so it finishes\n"
        "first - the queue still stops."
    )

    def refresh_queue() -> None:
        queue.clear()
        if runner.current is not None:
            queue.addItem(f"running: {runner.current.title}")
        for job in runner.queued:
            queue.addItem(f"queued:  {job.title}")
        stop.setEnabled(runner.busy or bool(runner.queued))
        _refresh_run()

    def refresh() -> None:
        refresh_queue()

    for form in forms.values():
        form.on_changed = _refresh_run

    box.refresh = refresh
    box.forms = forms
    box.chooser = chooser
    box.refresh_queue = refresh_queue
    refresh()
    return box


def outputs_of(result, app) -> tuple[list[Path], list[Path]]:
    """Split a finished job's outputs into (already open, new).

    Which one a file falls into decides whether the panel offers "reload" or "load",
    and those are different questions: reloading replaces what you are looking at.
    """
    open_paths = {
        _norm(getattr(app.args, dest, None))
        for dest in ("graph", "seg", "surface", "edits")
    }
    open_paths.discard(None)
    same, fresh = [], []
    for path in getattr(result, "outputs_written", ()):
        (same if _norm(path) in open_paths else fresh).append(Path(path))
    return same, fresh


def _norm(path):
    if not path:
        return None
    try:
        return str(Path(path).resolve()).lower()
    except OSError:
        return str(path).lower()
